[package]
name = "same_enum"
version = "0.1.2"
edition = "2021"
description = "Generates `From` trait implementations for enums with the same unit variants."
license = "MIT"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
